const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  TOUR_MANAGER: 'TOUR_MANAGER',
  TOUR_GUIDE: 'TOUR_GUIDE',
  CUSTOMER: 'CUSTOMER'
};

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  GUIDE_ASSIGNED: 'GUIDE_ASSIGNED',
  READY_FOR_TOUR: 'READY_FOR_TOUR',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

module.exports = {
  ROLES,
  BOOKING_STATUS,
  PAYMENT_STATUS
};
